### ISSUE TITLE
the issue about the Samsung s20 repos from you.

### ISSUE THREAD

**Issue by fun1355** [li-notfish/Logistics#2]
You have deleted the three repos about s20(x1q). My local_manifests.xml is:

```
 <?xml version="1.0" encoding="UTF-8"?>
 <manifest>
     <project path="device/samsung/x1q" remote="github" name="li-notfish/device_samsung_x1q" revision="master" />
     <project path="device/samsung/sm8250-common" remote="github" name="li-notfish/device_samsung_sm8250-common" revision="master" />
     <project path="kernel/samsung/sm8250" remote="github" name="li-notfish/kernal_samsung_sm8250" revision="main" />
     <project path="vendor/samsung/x1q" remote="github" name="li-notfish/proprietary_vendor_samsung_x1q" revision="master" />
     <project path="vendor/samsung/sm8250-common" remote="github" name="li-notfish/proprietary_vendor_samsung_sm8250" revision="master" />
     <!-- project path="device/samsung_slsi/sepolicy" remote="github" name="PixelExtended-Devices/device_samsung_slsi_sepolicy" revision="trece" / -->
     <project path="hardware/samsung" remote="github" name="PixelExtended-Devices/hardware_samsung" revision="trece" />
 </manifest>
```                        
                     
I nearly completed the build process( only ~30 tasks to compile), but abored by errors about Sepolicy conflicts. I changed one sepolicy and turn to produce more and more conflicts. 

Why I request this Issue is that I just wanna ask, do you finished building the rom? 
I did't have the Samsung S20 phone. Why I build the rom is to select one Samsung model to develop for My former company. Finally I have built the Samsung S20+.

**Comment by li-notfish** [comment]
No, it was only compiled successfully once. But when I flash in, I got stuck on the Samsung screen. I tried many modifications later but failed, and in the end, I changed my phone. If you want to built Samsung s20+ you can look other repos [miraclestars](https://github.com/miraclestars/android_device_samsung_y2qdcmw)
If there is a problem with your phone due to my repo, I'm sorry...

**Comment by fun1355** [comment]
Thanks all the same, I have compiled successfully once s20+, following miraclestars and others. But I don't flash the LineageOS ROM, I realised that the OneUI is good at cheating the upper apps than Pure aosp system, due that I develop it for a company to do evil work. If you wanna try another time on other devices from fresh, follow the guide from https://blog.lynnrin.moe/posts/ROM-bringup-guide-prebuilt/. May you an easy life.

**Comment by li-notfish** [comment]
> Thanks all the same, I have compiled successfully once s20+, following miraclestars and others. But I don't flash the LineageOS ROM, I realised that the OneUI is good at cheating the upper apps than Pure aosp system, due that I develop it for a company to do evil work. If you wanna try another time on other devices from fresh, follow the guide from https://blog.lynnrin.moe/posts/ROM-bringup-guide-prebuilt/. May you an easy life.

Okay, if only I could have seen this guide earlier. Wishing you well

**Comment by fun1355** [comment]
When your device bootlooped in 2nd screen, aka the Linux bringed up and fs mounted luckily, another tips: https://blog.xzr.moe/archives/112. BTW, the auther has lots of tips.
